---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-stuff
  description: Stuff API
  annotations:
    github.com/project-slug: ServerlessOpsIO/test-stuff
spec:
  type: api
  lifecycle: production
  owner: group:backstage
  system: system:backstage
  providesApis:
    - resource:test-stuff

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: test-stuff
  description: |
    Stuff API
    
    Manage stuff
spec:
  type: openapi
  system: system:backstage
  lifecycle: production
  owner: group:backstage
  definition:
    $text: https://github.com/ServerlessOpsIO/test-stuff/blob/main/openapi.yaml
